<?php

class Experius_DonationProduct_Model_Product_Type_Donation extends Mage_Catalog_Model_Product_Type_Abstract
{
    /**
     * Check is virtual product
     *
     * @param Mage_Catalog_Model_Product $product
     * @return bool
     */
    public function isVirtual($product = null)
    {
        return true;
    }

    public function _prepareProduct($buyRequest, $product, $processMode)
    {
        if (!$product->getCustomOption('donation_options')) {
            return $this->getSpecifyOptionMessage()->render();
        }

        return parent::_prepareProduct($buyRequest, $product, $processMode); // TODO: Change the autogenerated stub
    }

    public function prepareForCartAdvanced($buyRequest, $product, $processMode = null)
    {

        $typeId = $product->getTypeId();

        if ($typeId == 'donation') {
            $donationData['amount'] = $buyRequest->getData('amount');
            $product->addCustomOption('donation_options', json_encode($donationData));
        }

        return parent::prepareForCartAdvanced($buyRequest, $product, $processMode);
    }
}