<?php
/** @var Experius_DonationProduct_Block_Widget $this */

use Experius_DonationProduct_Model_Source_Display_Mode as DisplayMode;
?>
<section class="exp-donation">
    <header>
        <h3><?= $this->getTitle(); ?></h3>
    </header>
    <p>
        <?= $this->getText(); ?>
    </p>
    <?php /** @var Mage_Catalog_Model_Product $product */ ?>
    <?php foreach ($this->getProductCollection() as $product): ?>
        <article class="exp-donation-product">

            <a href="<?= $product->getProductUrl() ?>" title="<?= $product->getName(); ?>" class="exp-donation-product-link">
                <img src="<?= Mage::helper('catalog/image')->init($product, 'small_image')->resize(200); ?>" alt="<?= $product->getName(); ?>" class="exp-donation-product-image" />
            </a>

            <form id="donation-form-<?php echo $product->getId(); ?>" method="POST" action="<?php echo $this->getAddToCartUrl($product, array('_secure' => $this->_isSecure())) ?>">
                <?php echo $this->getBlockHtml('formkey') ?>

                <div class="form-list">
                    <?php if (in_array($product->getDisplayMode(), [DisplayMode::MODE_FIXED, DisplayMode::MODE_BOTH])): ?>
                        <div class="donation">
                            <?php echo $this->__('Choose an amount:'); ?>
                        </div>
                        <div class="fixed-amounts fixed-amounts-<?php echo $product->getId(); ?>">
                            <?php foreach ($this->helper('donationproduct')->getFixedAmounts() as $amount): ?>
                                <label class="donation-amount">
                                    <input type="radio" value="<?php echo $amount; ?>" name="amount">
                                    <span><?php echo Mage::app()->getStore()->formatPrice($amount);?></span>
                                </label>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>

                    <?php if (in_array($product->getDisplayMode(), [DisplayMode::MODE_INPUT, DisplayMode::MODE_BOTH])): ?>
                        <div class="field-input user-input">
                            <label class="donation-amount">
                                <?php if ($product->getDisplayMode() === DisplayMode::MODE_BOTH): ?>
                                    <span><?php echo $this->__('Or enter an amount in %s', Mage::app()->getStore()->getCurrentCurrencyCode()); ?></span>
                                <?php else: ?>
                                    <span><?php echo $this->__('Enter an amount in %s', Mage::app()->getStore()->getCurrentCurrencyCode()); ?></span>
                                <?php endif; ?>
                                <input name="amount" class="user-input required-entry" id="user-input-<?php echo $product->getId(); ?>" value="<?php echo $this->helper('donationproduct')->getMinAmount($product); ?>">
                            </label>
                        </div>
                    <?php endif; ?>

                </div>
                <button type="submit" id="donate-button-<?php echo $product->getId(); ?>" class="btn btn-default"><?php echo $this->__('Donate'); ?></button>
            </form>

            <script type="text/javascript">
                //<![CDATA[
                (function () {
                    var formId = 'donation-form-<?php echo $product->getId(); ?>';
                    var form = new VarienForm(formId, true);
                    var action = $(formId).action;
                    function doAjax() {
                        if (form.validator.validate()) {
                            new Ajax.Updater(
                                { success:'formSuccess' }, action, {
                                    method:'post',
                                    asynchronous:true,
                                    evalScripts:false,
                                    onComplete:function(request, json) {
                                        location.reload();
                                    },
                                    onLoading:function(request, json){
                                        Element.disable('donate-button-<?php echo $product->getId(); ?>');
                                    },
                                    parameters: $(formId).serialize(true),
                                }
                            );
                        }
                    }

                    Event.observe(formId, 'submit', function(e){
                        e.stop();
                        doAjax();
                    });
                })();
                //]]>
            </script>

        </article>

        <?php if ($product->getDisplayMode() === DisplayMode::MODE_BOTH): ?>
            <script type="text/javascript">
                $('user-input-<?php echo $product->getId(); ?>').observe('keypress', function () {
                    $$('.fixed-amounts-<?php echo $product->getId(); ?> input[type="radio"]').each(function (element) {
                        element.checked = false;
                    });
                });

                $$('.fixed-amounts-<?php echo $product->getId(); ?> input[type="radio"]').each(function (element) {
                    element.observe('click', function () {
                        if (element.checked) {
                            $('user-input-<?php echo $product->getId(); ?>').value = element.value;
                        }
                    });
                });
            </script>
        <?php endif; ?>
    <?php endforeach; ?>
</section>
